
nodeSelector:
  workload-role: monitoring

tolerations:
  - key: dedicated
    operator: Equal
    value: monitoring
    effect: NoSchedule

persistence:
  enabled: true
  type: pvc
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  size: 2Gi

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

adminUser: admin

grafana.ini:
  users:
    allow_sign_up: false

  analytics:
    reporting_enabled: false
    check_for_updates: false
